-- =============================================
-- Sample Seed Data for Chat Application
-- Run AFTER all schema and procedure scripts.
-- =============================================

-- Note: These UUIDs are placeholders. In production,
-- real UUIDs would be generated by the application.

-- ============================================
-- SAMPLE USER SETTINGS (for user1_uuid)
-- ============================================
-- Use the actual user ID from your users table.
-- Example assumes user IDs exist.

-- INSERT INTO user_settings (user_id, setting_key, setting_value) VALUES
-- ('USER1_UUID', 'privacy_onlineStatus', '"everyone"'),
-- ('USER1_UUID', 'privacy_lastSeen', '"contacts"'),
-- ('USER1_UUID', 'privacy_profilePhoto', '"everyone"'),
-- ('USER1_UUID', 'notifications_messages', 'true'),
-- ('USER1_UUID', 'notifications_groups', 'true'),
-- ('USER1_UUID', 'notifications_contacts', 'true'),
-- ('USER1_UUID', 'notifications_sound', 'true'),
-- ('USER1_UUID', 'chat_enterSends', 'true'),
-- ('USER1_UUID', 'chat_fontSize', '"medium"'),
-- ('USER1_UUID', 'theme', '"light"')
-- ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);


-- ============================================
-- SAMPLE NOTIFICATIONS (for user1_uuid)
-- ============================================
-- INSERT INTO notifications (user_id, type, title, message, data, is_read) VALUES
-- ('USER1_UUID', 'new_message', 'New Message', 'You have a new message from John', '{"conversationId": "CONV_UUID"}', 0),
-- ('USER1_UUID', 'group_invite', 'Group Invite', 'You have been invited to join "Project Team"', '{"groupId": "GROUP_UUID"}', 0),
-- ('USER1_UUID', 'user_online', 'Contact Online', 'Jane is now online', '{"userId": "USER2_UUID"}', 1),
-- ('USER1_UUID', 'mention', 'You were mentioned', 'John mentioned you in "General Chat"', '{"conversationId": "CONV_UUID", "messageId": "MSG_UUID"}', 0);


-- ============================================
-- SAMPLE SCHEDULED MESSAGES
-- ============================================
-- INSERT INTO scheduled_messages (sender_id, conversation_id, content, message_type, scheduled_at, status) VALUES
-- ('USER1_UUID', 'CONV_UUID', 'Good morning! This is a scheduled greeting.', 'text', DATE_ADD(NOW(), INTERVAL 1 HOUR), 'pending'),
-- ('USER1_UUID', 'CONV_UUID', 'Reminder: Team meeting at 3 PM today.', 'text', DATE_ADD(NOW(), INTERVAL 3 HOUR), 'pending');


-- ============================================
-- VERIFICATION QUERIES
-- ============================================
-- Run these to verify tables were created properly:

-- SELECT 'scheduled_messages' AS table_name, COUNT(*) AS row_count FROM scheduled_messages
-- UNION ALL
-- SELECT 'user_settings', COUNT(*) FROM user_settings
-- UNION ALL
-- SELECT 'notifications', COUNT(*) FROM notifications;

-- Verify stored procedures exist:
-- SELECT ROUTINE_NAME, ROUTINE_TYPE
-- FROM INFORMATION_SCHEMA.ROUTINES
-- WHERE ROUTINE_SCHEMA = DATABASE()
--   AND ROUTINE_NAME LIKE 'sp_%'
-- ORDER BY ROUTINE_NAME;
